version: '3.2'

services:
  app:
    image: eu.gcr.io/k8s-worshop/app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD
    ports:
      - 9000
