apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: app
spec:
  replicas: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: eu.gcr.io/k8s-worshop/app:step6
        ports:
          - containerPort: 9000
        env:
          - name: REDIS_HOST
            value: redis